#ifndef _BITS_STDINT_INTN_H
#define _BITS_STDINT_INTN_H

// Warning: This file was autogenerated with cbindgen.
// To add bindings, edit the source and rerun cbindgen.

typedef signed char int8_t;

typedef short int16_t;

typedef int int32_t;

typedef long long int64_t;

typedef signed char rint_fast8_t;

typedef short rint_fast16_t;

typedef int rint_fast32_t;

typedef long long rint_fast64_t;

typedef signed char rint_least8_t;

typedef short rint_least16_t;

typedef int rint_least32_t;

typedef long long rint_least64_t;

void _use_types_stdint_intn_h(int8_t,
                              int16_t,
                              int32_t,
                              int64_t,
                              rint_fast8_t,
                              rint_fast16_t,
                              rint_fast32_t,
                              rint_fast64_t,
                              rint_least8_t,
                              rint_least16_t,
                              rint_least32_t,
                              rint_least64_t);

#endif /* _BITS_STDINT_INTN_H */
