#ifndef _BITS_STDINT_UINTN_H
#define _BITS_STDINT_UINTN_H

// Warning: This file was autogenerated with cbindgen.
// To add bindings, edit the source and rerun cbindgen.

typedef unsigned char uint8_t;

typedef unsigned short uint16_t;

typedef unsigned int uint32_t;

typedef unsigned long long uint64_t;

typedef unsigned char ruint_fast8_t;

typedef unsigned short ruint_fast16_t;

typedef unsigned int ruint_fast32_t;

typedef unsigned long long ruint_fast64_t;

typedef unsigned char ruint_least8_t;

typedef unsigned short ruint_least16_t;

typedef unsigned int ruint_least32_t;

typedef unsigned long long ruint_least64_t;

void _use_types_stdint_uintn_h(uint8_t,
                               uint16_t,
                               uint32_t,
                               uint64_t,
                               ruint_fast8_t,
                               ruint_fast16_t,
                               ruint_fast32_t,
                               ruint_fast64_t,
                               ruint_least8_t,
                               ruint_least16_t,
                               ruint_least32_t,
                               ruint_least64_t);

#endif /* _BITS_STDINT_UINTN_H */
