#ifndef _BITS_STDINT_UINTN_H
#define _BITS_STDINT_UINTN_H

// Warning: This file was autogenerated with cbindgen.
// To add bindings, edit the source and rerun cbindgen.

typedef unsigned char uint8_t;

typedef unsigned short uint16_t;

typedef unsigned int uint32_t;

#if defined(__WORDSIZE) && (__WORDSIZE == 64)
typedef unsigned long uint64_t;
#endif

typedef unsigned long long uint64_t;

void __use_types_stdint_uintn_h(uint8_t, uint16_t, uint32_t, uint64_t);

#endif /* _BITS_STDINT_UINTN_H */
