#ifndef NOVUSK_ENTRY_H
#define NOVUSK_ENTRY_H

#define S_FRAME_SIZE 256

#define INVALID_SYNCEL1t 0
#define INVALID_IRQEL1t 1
#define INVALID_FIQEL1t 2
#define INVALID_ERROREL1t 3

#define INVALID_SYNCEL1h 4
#define INVALID_IRQEL1h 5
#define INVALID_FIQEL1h 6
#define INVALID_ERROREL1h 7

#define INVALID_SYNCEL0_64 8
#define INVALID_IRQEL0_64 9
#define INVALID_FIQEL0_64 10
#define INVALID_ERROREL0_64 11

#define INVALID_SYNCEL0t_32 12
#define INVALID_IRQEL0t_32 13
#define INVALID_FIQEL0t_32 14
#define INVALID_ERROREL0t_32 15

entry_error:
    wfe
    b .

#endif //NOVUSK_ENTRY_H
