#ifndef _STDDEF_H
#define _STDDEF_H

// Warning: This file was autogenerated with cbindgen.
// To add bindings, edit the source and rerun cbindgen.

typedef unsigned long size_t;

void __use_types(size_t);

#endif /* _STDDEF_H */
