#ifndef _STDINT_H
#define _STDINT_H

// Warning: This file was autogenerated with cbindgen.
// To add bindings, edit the source and rerun cbindgen.

#include "bits/stdint-intn.h"
#include "bits/stdint-uintn.h"

#define INT8_MIN -128

#define INT16_MIN (-32767 - 1)

#define INT32_MIN (-2147483647 - 1)

#if defined(__WORDSIZE) && (__WORDSIZE == 64)
#define INT64_MIN (-9223372036854775807 - 1)
#endif

#define INT64_MIN (-2147483647 - 1)

#define INT8_MAX 127

#define INT16_MAX 32767

#define INT32_MAX 2147483647

#if defined(__WORDSIZE) && (__WORDSIZE == 64)
#define INT64_MAX 9223372036854775807
#endif

#define INT64_MAX 2147483647

#define UINT8_MIN 0

#define UINT16_MIN 0

#define UINT32_MIN 0

#if defined(__WORDSIZE) && (__WORDSIZE == 64)
#define UINT64_MIN 0
#endif

#define UINT64_MIN 0

#define UINT8_MAX 255

#define UINT16_MAX 65535

#define UINT32_MAX 4294967295

#if defined(__WORDSIZE) && (__WORDSIZE == 64)
#define UINT64_MAX 18446744073709551615ull
#endif

#define UINT64_MAX 4294967295

#define INT8_WIDTH 8

#define INT16_WIDTH 16

#define INT32_WIDTH 32

#if defined(__WORDSIZE) && (__WORDSIZE == 64)
#define INT64_WIDTH 64
#endif

#define INT64_WIDTH 32

#define UINT8_WIDTH 8

#define UINT16_WIDTH 16

#define UINT32_WIDTH 32

#if defined(__WORDSIZE) && (__WORDSIZE == 64)
#define UINT64_WIDTH 64
#endif

#define UINT64_WIDTH 32

#endif /* _STDINT_H */
