[package]
name = "nkernel"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
cortex-m-semihosting = "0.5.0"
novuskinc = { git = "https://github.com/new-kernel/novuskinc" }

[features]
inc_dev_drivers = []
no_alloc = []
no_oom = []
no_panic = []
