[package]
name = "multiboot"
version = "0.1.0"
edition = "2021"
description = "Setup for multibooted kernel"
license = "MIT"
publish = false

[dependencies]
multiboot2 = "0.14.0"
# printk = { path = "../../../kernel/printk/" }
