use ctypes::{c_char, macro_int};

pub const CONFIG_IDF_TARGET: *const c_char = "esp32".as_ptr() as *const c_char;
pub const CONFIG_IDF_TARGET_ESP32: macro_int = 1;
pub const CONFIG_IDF_FIRMWARE_CHIP_ID: macro_int = 0x0000;
pub const CONFIG_SDK_TOOLPREFIX: *const c_char = "xtensa-esp32-elf-".as_ptr() as *const c_char;
pub const CONFIG_APP_BUILD_TYPE_APP_2NDBOOT: macro_int = 1;
pub const CONFIG_APP_BUILD_GENERATE_BINARIES: macro_int = 1;
pub const CONFIG_APP_BUILD_BOOTLOADER: macro_int = 1;
pub const CONFIG_APP_BUILD_USE_FLASH_SECTIONS: macro_int = 1;
pub const CONFIG_APP_COMPILE_TIME_DATE: macro_int = 1;
pub const CONFIG_APP_RETRIEVE_LEN_ELF_SHA: macro_int = 16;
pub const CONFIG_BOOTLOADER_COMPILER_OPTIMIZATION_SIZE: macro_int = 1;
pub const CONFIG_BOOTLOADER_LOG_LEVEL_INFO: macro_int = 1;
pub const CONFIG_BOOTLOADER_LOG_LEVEL: macro_int = 3;
pub const CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V: macro_int = 1;
pub const CONFIG_BOOTLOADER_WDT_ENABLE: macro_int = 1;
pub const CONFIG_BOOTLOADER_WDT_TIME_MS: macro_int = 9000;
pub const CONFIG_BOOTLOADER_RESERVE_RTC_SIZE: macro_int = 0x0;
pub const CONFIG_ESPTOOLPY_BAUD_OTHER_VAL: macro_int = 115200;
pub const CONFIG_ESPTOOLPY_FLASHMODE_DIO: macro_int = 1;
pub const CONFIG_ESPTOOLPY_FLASHMODE: *const c_char = "dio".as_ptr() as *const c_char;
pub const CONFIG_ESPTOOLPY_FLASHFREQ_40M: macro_int = 1;
pub const CONFIG_ESPTOOLPY_FLASHFREQ: *const c_char = "40m".as_ptr() as *const c_char;
pub const CONFIG_ESPTOOLPY_FLASHSIZE_2MB: macro_int = 1;
pub const CONFIG_ESPTOOLPY_FLASHSIZE: *const c_char = "2MB".as_ptr() as *const c_char;
pub const CONFIG_ESPTOOLPY_FLASHSIZE_DETECT: macro_int = 1;
pub const CONFIG_ESPTOOLPY_BEFORE_RESET: macro_int = 1;
pub const CONFIG_ESPTOOLPY_BEFORE: *const c_char = "default_reset".as_ptr() as *const c_char;
pub const CONFIG_ESPTOOLPY_AFTER_RESET: macro_int = 1;
pub const CONFIG_ESPTOOLPY_AFTER: *const c_char = "hard_reset".as_ptr() as *const c_char;
pub const CONFIG_ESPTOOLPY_MONITOR_BAUD_115200B: macro_int = 1;
pub const CONFIG_ESPTOOLPY_MONITOR_BAUD_OTHER_VAL: macro_int = 115200;
pub const CONFIG_ESPTOOLPY_MONITOR_BAUD: macro_int = 115200;
pub const CONFIG_PARTITION_TABLE_SINGLE_APP: macro_int = 1;
pub const CONFIG_PARTITION_TABLE_CUSTOM_FILENAME: *const c_char = "partitions.csv".as_ptr() as *const c_char;
pub const CONFIG_PARTITION_TABLE_FILENAME: *const c_char = "partitions_singleapp.csv".as_ptr() as *const c_char;
pub const CONFIG_PARTITION_TABLE_OFFSET: macro_int = 0x8000;
pub const CONFIG_PARTITION_TABLE_MD5: macro_int = 1;
pub static mut CONFIG_ESP_WIFI_SSID: *const c_char = "myssid".as_ptr() as *const c_char;
pub static mut CONFIG_ESP_WIFI_PASSWORD: *const c_char = "mypassword".as_ptr() as *const c_char;
pub const CONFIG_ESP_MAXIMUM_RETRY: macro_int = 5;
pub const CONFIG_COMPILER_OPTIMIZATION_DEFAULT: macro_int = 1;
pub const CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_ENABLE: macro_int = 1;
pub const CONFIG_COMPILER_STACK_CHECK_MODE_NONE: macro_int = 1;
pub const CONFIG_APPTRACE_DEST_NONE: macro_int = 1;
pub const CONFIG_APPTRACE_LOCK_ENABLE: macro_int = 1;
pub const CONFIG_BTDM_CTRL_BR_EDR_SCO_DATA_PATH_EFF: macro_int = 0;
pub const CONFIG_BTDM_CTRL_BLE_MAX_CONN_EFF: macro_int = 0;
pub const CONFIG_BTDM_CTRL_BR_EDR_MAX_ACL_CONN_EFF: macro_int = 0;
pub const CONFIG_BTDM_CTRL_BR_EDR_MAX_SYNC_CONN_EFF: macro_int = 0;
pub const CONFIG_BTDM_CTRL_PINNED_TO_CORE: macro_int = 0;
pub const CONFIG_BTDM_BLE_SLEEP_CLOCK_ACCURACY_INDEX_EFF: macro_int = 1;
pub const CONFIG_BT_RESERVE_DRAM: macro_int = 0x0;
pub const CONFIG_COAP_MBEDTLS_PSK: macro_int = 1;
pub const CONFIG_COAP_LOG_DEFAULT_LEVEL: macro_int = 0;
pub const CONFIG_ADC_DISABLE_DAC: macro_int = 1;
pub const CONFIG_SPI_MASTER_ISR_IN_IRAM: macro_int = 1;
pub const CONFIG_SPI_SLAVE_ISR_IN_IRAM: macro_int = 1;
pub const CONFIG_EFUSE_CODE_SCHEME_COMPAT_3_4: macro_int = 1;
pub const CONFIG_EFUSE_MAX_BLK_LEN: macro_int = 192;
pub const CONFIG_ESP_TLS_USING_MBEDTLS: macro_int = 1;
pub const CONFIG_ESP32_REV_MIN_0: macro_int = 1;
pub const CONFIG_ESP32_REV_MIN: macro_int = 0;
pub const CONFIG_ESP32_DPORT_WORKAROUND: macro_int = 1;
pub const CONFIG_ESP32_DEFAULT_CPU_FREQ_160: macro_int = 1;
pub const CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: macro_int = 160;
pub const CONFIG_ESP32_TRACEMEM_RESERVE_DRAM: macro_int = 0x0;
pub const CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES_FOUR: macro_int = 1;
pub const CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES: macro_int = 4;
pub const CONFIG_ESP32_ULP_COPROC_RESERVE_MEM: macro_int = 0;
pub const CONFIG_ESP32_PANIC_PRINT_REBOOT: macro_int = 1;
pub const CONFIG_ESP32_DEBUG_OCDAWARE: macro_int = 1;
pub const CONFIG_ESP32_BROWNOUT_DET: macro_int = 1;
pub const CONFIG_ESP32_BROWNOUT_DET_LVL_SEL_0: macro_int = 1;
pub const CONFIG_ESP32_BROWNOUT_DET_LVL: macro_int = 0;
pub const CONFIG_ESP32_REDUCE_PHY_TX_POWER: macro_int = 1;
pub const CONFIG_ESP32_TIME_SYSCALL_USE_RTC_FRC1: macro_int = 1;
pub const CONFIG_ESP32_RTC_CLK_SRC_INT_RC: macro_int = 1;
pub const CONFIG_ESP32_RTC_CLK_CAL_CYCLES: macro_int = 1024;
pub const CONFIG_ESP32_DEEP_SLEEP_WAKEUP_DELAY: macro_int = 2000;
pub const CONFIG_ESP32_XTAL_FREQ_40: macro_int = 1;
pub const CONFIG_ESP32_XTAL_FREQ: macro_int = 40;
pub const CONFIG_ESP32_DPORT_DIS_INTERRUPT_LVL: macro_int = 5;
pub const CONFIG_ADC_CAL_EFUSE_TP_ENABLE: macro_int = 1;
pub const CONFIG_ADC_CAL_EFUSE_VREF_ENABLE: macro_int = 1;
pub const CONFIG_ADC_CAL_LUT_ENABLE: macro_int = 1;
pub const CONFIG_ESP_ERR_TO_NAME_LOOKUP: macro_int = 1;
pub const CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE: macro_int = 32;
pub const CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE: macro_int = 2304;
pub const CONFIG_ESP_MAIN_TASK_STACK_SIZE: macro_int = 3584;
pub const CONFIG_ESP_IPC_TASK_STACK_SIZE: macro_int = 1024;
pub const CONFIG_ESP_IPC_USES_CALLERS_PRIORITY: macro_int = 1;
pub const CONFIG_ESP_TIMER_TASK_STACK_SIZE: macro_int = 3584;
pub const CONFIG_ESP_MINIMAL_SHARED_STACK_SIZE: macro_int = 2048;
pub const CONFIG_ESP_CONSOLE_UART_DEFAULT: macro_int = 1;
pub const CONFIG_ESP_CONSOLE_UART_NUM: macro_int = 0;
pub const CONFIG_ESP_CONSOLE_UART_BAUDRATE: macro_int = 115200;
pub const CONFIG_ESP_INT_WDT: macro_int = 1;
pub const CONFIG_ESP_INT_WDT_TIMEOUT_MS: macro_int = 300;
pub const CONFIG_ESP_INT_WDT_CHECK_CPU1: macro_int = 1;
pub const CONFIG_ESP_TASK_WDT: macro_int = 1;
pub const CONFIG_ESP_TASK_WDT_TIMEOUT_S: macro_int = 5;
pub const CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0: macro_int = 1;
pub const CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1: macro_int = 1;
pub const CONFIG_ETH_ENABLED: macro_int = 1;
pub const CONFIG_ETH_USE_ESP32_EMAC: macro_int = 1;
pub const CONFIG_ETH_PHY_INTERFACE_RMII: macro_int = 1;
pub const CONFIG_ETH_RMII_CLK_INPUT: macro_int = 1;
pub const CONFIG_ETH_RMII_CLK_IN_GPIO: macro_int = 0;
pub const CONFIG_ETH_DMA_BUFFER_SIZE: macro_int = 512;
pub const CONFIG_ETH_DMA_RX_BUFFER_NUM: macro_int = 10;
pub const CONFIG_ETH_DMA_TX_BUFFER_NUM: macro_int = 10;
pub const CONFIG_ETH_USE_SPI_ETHERNET: macro_int = 1;
pub const CONFIG_ETH_SPI_ETHERNET_DM9051: macro_int = 1;
pub const CONFIG_ESP_EVENT_POST_FROM_ISR: macro_int = 1;
pub const CONFIG_ESP_EVENT_POST_FROM_IRAM_ISR: macro_int = 1;
pub const CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS: macro_int = 1;
pub const CONFIG_HTTPD_MAX_REQ_HDR_LEN: macro_int = 512;
pub const CONFIG_HTTPD_MAX_URI_LEN: macro_int = 512;
pub const CONFIG_HTTPD_ERR_RESP_NO_DELAY: macro_int = 1;
pub const CONFIG_HTTPD_PURGE_BUF_LEN: macro_int = 32;
pub const CONFIG_ESP_NETIF_IP_LOST_TIMER_INTERVAL: macro_int = 120;
pub const CONFIG_ESP_NETIF_TCPIP_LWIP: macro_int = 1;
pub const CONFIG_ESP_NETIF_TCPIP_ADAPTER_COMPATIBLE_LAYER: macro_int = 1;
pub const CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: macro_int = 10;
pub const CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: macro_int = 32;
pub const CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER: macro_int = 1;
pub const CONFIG_ESP32_WIFI_TX_BUFFER_TYPE: macro_int = 1;
pub const CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM: macro_int = 32;
pub const CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED: macro_int = 1;
pub const CONFIG_ESP32_WIFI_TX_BA_WIN: macro_int = 6;
pub const CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED: macro_int = 1;
pub const CONFIG_ESP32_WIFI_RX_BA_WIN: macro_int = 6;
pub const CONFIG_ESP32_WIFI_NVS_ENABLED: macro_int = 1;
pub const CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_0: macro_int = 1;
pub const CONFIG_ESP32_WIFI_SOFTAP_BEACON_MAX_LEN: macro_int = 752;
pub const CONFIG_ESP32_WIFI_MGMT_SBUF_NUM: macro_int = 32;
pub const CONFIG_ESP32_WIFI_IRAM_OPT: macro_int = 1;
pub const CONFIG_ESP32_WIFI_RX_IRAM_OPT: macro_int = 1;
pub const CONFIG_ESP32_WIFI_ENABLE_WPA3_SAE: macro_int = 1;
pub const CONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE: macro_int = 1;
pub const CONFIG_ESP32_PHY_MAX_WIFI_TX_POWER: macro_int = 20;
pub const CONFIG_ESP32_PHY_MAX_TX_POWER: macro_int = 20;
pub const CONFIG_ESP32_ENABLE_COREDUMP_TO_NONE: macro_int = 1;
pub const CONFIG_FATFS_CODEPAGE_437: macro_int = 1;
pub const CONFIG_FATFS_CODEPAGE: macro_int = 437;
pub const CONFIG_FATFS_LFN_NONE: macro_int = 1;
pub const CONFIG_FATFS_FS_LOCK: macro_int = 0;
pub const CONFIG_FATFS_TIMEOUT_MS: macro_int = 10000;
pub const CONFIG_FATFS_PER_FILE_CACHE: macro_int = 1;
pub const CONFIG_FMB_COMM_MODE_RTU_EN: macro_int = 1;
pub const CONFIG_FMB_COMM_MODE_ASCII_EN: macro_int = 1;
pub const CONFIG_FMB_MASTER_TIMEOUT_MS_RESPOND: macro_int = 150;
pub const CONFIG_FMB_MASTER_DELAY_MS_CONVERT: macro_int = 200;
pub const CONFIG_FMB_QUEUE_LENGTH: macro_int = 20;
pub const CONFIG_FMB_SERIAL_TASK_STACK_SIZE: macro_int = 2048;
pub const CONFIG_FMB_SERIAL_BUF_SIZE: macro_int = 256;
pub const CONFIG_FMB_SERIAL_ASCII_BITS_PER_SYMB: macro_int = 8;
pub const CONFIG_FMB_SERIAL_ASCII_TIMEOUT_RESPOND_MS: macro_int = 1000;
pub const CONFIG_FMB_SERIAL_TASK_PRIO: macro_int = 10;
pub const CONFIG_FMB_CONTROLLER_NOTIFY_TIMEOUT: macro_int = 20;
pub const CONFIG_FMB_CONTROLLER_NOTIFY_QUEUE_SIZE: macro_int = 20;
pub const CONFIG_FMB_CONTROLLER_STACK_SIZE: macro_int = 4096;
pub const CONFIG_FMB_EVENT_QUEUE_TIMEOUT: macro_int = 20;
pub const CONFIG_FMB_TIMER_PORT_ENABLED: macro_int = 1;
pub const CONFIG_FMB_TIMER_GROUP: macro_int = 0;
pub const CONFIG_FMB_TIMER_INDEX: macro_int = 0;
pub const CONFIG_FREERTOS_NO_AFFINITY: macro_int = 0x7FFFFFFF;
pub const CONFIG_FREERTOS_CORETIMER_0: macro_int = 1;
pub const CONFIG_FREERTOS_HZ: macro_int = 100;
pub const CONFIG_FREERTOS_ASSERT_ON_UNTESTED_FUNCTION: macro_int = 1;
pub const CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY: macro_int = 1;
pub const CONFIG_FREERTOS_INTERRUPT_BACKTRACE: macro_int = 1;
pub const CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS: macro_int = 1;
pub const CONFIG_FREERTOS_ASSERT_FAIL_ABORT: macro_int = 1;
pub const CONFIG_FREERTOS_IDLE_TASK_STACKSIZE: macro_int = 1536;
pub const CONFIG_FREERTOS_ISR_STACKSIZE: macro_int = 1536;
pub const CONFIG_FREERTOS_MAX_TASK_NAME_LEN: macro_int = 16;
pub const CONFIG_FREERTOS_TIMER_TASK_PRIORITY: macro_int = 1;
pub const CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH: macro_int = 2048;
pub const CONFIG_FREERTOS_TIMER_QUEUE_LENGTH: macro_int = 10;
pub const CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE: macro_int = 0;
pub const CONFIG_FREERTOS_TASK_FUNCTION_WRAPPER: macro_int = 1;
pub const CONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER: macro_int = 1;
pub const CONFIG_FREERTOS_DEBUG_OCDAWARE: macro_int = 1;
pub const CONFIG_HEAP_POISONING_DISABLED: macro_int = 1;
pub const CONFIG_HEAP_TRACING_OFF: macro_int = 1;
pub const CONFIG_LOG_DEFAULT_LEVEL_INFO: macro_int = 1;
pub const CONFIG_LOG_DEFAULT_LEVEL: macro_int = 3;
pub const CONFIG_LOG_COLORS: macro_int = 1;
/*
pub const CONFIG_LOG_TIMESTAMP_SOURCE_RTOS 1
pub const CONFIG_LWIP_LOCAL_HOSTNAME "espressif"
pub const CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES 1
pub const CONFIG_LWIP_TIMERS_ONDEMAND 1
pub const CONFIG_LWIP_MAX_SOCKETS 10
pub const CONFIG_LWIP_SO_REUSE 1
pub const CONFIG_LWIP_SO_REUSE_RXTOALL 1
pub const CONFIG_LWIP_IP_FRAG 1
pub const CONFIG_LWIP_ESP_GRATUITOUS_ARP 1
pub const CONFIG_LWIP_GARP_TMR_INTERVAL 60
pub const CONFIG_LWIP_TCPIP_RECVMBOX_SIZE 32
pub const CONFIG_LWIP_DHCP_DOES_ARP_CHECK 1
pub const CONFIG_LWIP_DHCPS_LEASE_UNIT 60
pub const CONFIG_LWIP_DHCPS_MAX_STATION_NUM 8
pub const CONFIG_LWIP_NETIF_LOOPBACK 1
pub const CONFIG_LWIP_LOOPBACK_MAX_PBUFS 8
pub const CONFIG_LWIP_MAX_ACTIVE_TCP 16
pub const CONFIG_LWIP_MAX_LISTENING_TCP 16
pub const CONFIG_LWIP_TCP_MAXRTX 12
pub const CONFIG_LWIP_TCP_SYNMAXRTX 6
pub const CONFIG_LWIP_TCP_MSS 1440
pub const CONFIG_LWIP_TCP_TMR_INTERVAL 250
pub const CONFIG_LWIP_TCP_MSL 60000
pub const CONFIG_LWIP_TCP_SND_BUF_DEFAULT 5744
pub const CONFIG_LWIP_TCP_WND_DEFAULT 5744
pub const CONFIG_LWIP_TCP_RECVMBOX_SIZE 6
pub const CONFIG_LWIP_TCP_QUEUE_OOSEQ 1
pub const CONFIG_LWIP_TCP_OVERSIZE_MSS 1
pub const CONFIG_LWIP_MAX_UDP_PCBS 16
pub const CONFIG_LWIP_UDP_RECVMBOX_SIZE 6
pub const CONFIG_LWIP_TCPIP_TASK_STACK_SIZE 3072
pub const CONFIG_LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY 1
pub const CONFIG_LWIP_TCPIP_TASK_AFFINITY 0x7FFFFFFF
pub const CONFIG_LWIP_MAX_RAW_PCBS 16
pub const CONFIG_LWIP_DHCP_MAX_NTP_SERVERS 1
pub const CONFIG_LWIP_SNTP_UPDATE_DELAY 3600000
pub const CONFIG_MBEDTLS_INTERNAL_MEM_ALLOC 1
pub const CONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN 1
pub const CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN 16384
pub const CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN 4096
pub const CONFIG_MBEDTLS_HARDWARE_AES 1
pub const CONFIG_MBEDTLS_HARDWARE_MPI 1
pub const CONFIG_MBEDTLS_HARDWARE_SHA 1
pub const CONFIG_MBEDTLS_HAVE_TIME 1
pub const CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT 1
pub const CONFIG_MBEDTLS_TLS_SERVER 1
pub const CONFIG_MBEDTLS_TLS_CLIENT 1
pub const CONFIG_MBEDTLS_TLS_ENABLED 1
pub const CONFIG_MBEDTLS_PSK_MODES 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_PSK 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_PSK 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_PSK 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_PSK 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_RSA 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_RSA 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA 1
pub const CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA 1
pub const CONFIG_MBEDTLS_SSL_RENEGOTIATION 1
pub const CONFIG_MBEDTLS_SSL_PROTO_TLS1 1
pub const CONFIG_MBEDTLS_SSL_PROTO_TLS1_1 1
pub const CONFIG_MBEDTLS_SSL_PROTO_TLS1_2 1
pub const CONFIG_MBEDTLS_SSL_PROTO_DTLS 1
pub const CONFIG_MBEDTLS_SSL_ALPN 1
pub const CONFIG_MBEDTLS_CLIENT_SSL_SESSION_TICKETS 1
pub const CONFIG_MBEDTLS_SERVER_SSL_SESSION_TICKETS 1
pub const CONFIG_MBEDTLS_AES_C 1
pub const CONFIG_MBEDTLS_RC4_DISABLED 1
pub const CONFIG_MBEDTLS_CCM_C 1
pub const CONFIG_MBEDTLS_GCM_C 1
pub const CONFIG_MBEDTLS_PEM_PARSE_C 1
pub const CONFIG_MBEDTLS_PEM_WRITE_C 1
pub const CONFIG_MBEDTLS_X509_CRL_PARSE_C 1
pub const CONFIG_MBEDTLS_X509_CSR_PARSE_C 1
pub const CONFIG_MBEDTLS_ECP_C 1
pub const CONFIG_MBEDTLS_ECDH_C 1
pub const CONFIG_MBEDTLS_ECDSA_C 1
pub const CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED 1
pub const CONFIG_MBEDTLS_ECP_NIST_OPTIM 1
pub const CONFIG_MDNS_MAX_SERVICES 10
pub const CONFIG_MDNS_TASK_PRIORITY 1
pub const CONFIG_MDNS_TASK_AFFINITY_CPU0 1
pub const CONFIG_MDNS_TASK_AFFINITY 0x0
pub const CONFIG_MDNS_SERVICE_ADD_TIMEOUT_MS 2000
pub const CONFIG_MDNS_TIMER_PERIOD_MS 100
pub const CONFIG_MQTT_PROTOCOL_311 1
pub const CONFIG_MQTT_TRANSPORT_SSL 1
pub const CONFIG_MQTT_TRANSPORT_WEBSOCKET 1
pub const CONFIG_MQTT_TRANSPORT_WEBSOCKET_SECURE 1
pub const CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF 1
pub const CONFIG_NEWLIB_STDIN_LINE_ENDING_CR 1
pub const CONFIG_OPENSSL_ASSERT_EXIT 1
pub const CONFIG_PTHREAD_TASK_PRIO_DEFAULT 5
pub const CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT 3072
pub const CONFIG_PTHREAD_STACK_MIN 768
pub const CONFIG_PTHREAD_DEFAULT_CORE_NO_AFFINITY 1
pub const CONFIG_PTHREAD_TASK_CORE_DEFAULT -1
pub const CONFIG_PTHREAD_TASK_NAME_DEFAULT "pthread"
pub const CONFIG_SPI_FLASH_ROM_DRIVER_PATCH 1
pub const CONFIG_SPI_FLASH_DANGEROUS_WRITE_ABORTS 1
pub const CONFIG_SPI_FLASH_YIELD_DURING_ERASE 1
pub const CONFIG_SPI_FLASH_ERASE_YIELD_DURATION_MS 20
pub const CONFIG_SPI_FLASH_ERASE_YIELD_TICKS 1
pub const CONFIG_SPI_FLASH_SUPPORT_ISSI_CHIP 1
pub const CONFIG_SPI_FLASH_SUPPORT_GD_CHIP 1
pub const CONFIG_SPIFFS_MAX_PARTITIONS 3
pub const CONFIG_SPIFFS_CACHE 1
pub const CONFIG_SPIFFS_CACHE_WR 1
pub const CONFIG_SPIFFS_PAGE_CHECK 1
pub const CONFIG_SPIFFS_GC_MAX_RUNS 10
pub const CONFIG_SPIFFS_PAGE_SIZE 256
pub const CONFIG_SPIFFS_OBJ_NAME_LEN 32
pub const CONFIG_SPIFFS_USE_MAGIC 1
pub const CONFIG_SPIFFS_USE_MAGIC_LENGTH 1
pub const CONFIG_SPIFFS_META_LENGTH 4
pub const CONFIG_SPIFFS_USE_MTIME 1
pub const CONFIG_UNITY_ENABLE_FLOAT 1
pub const CONFIG_UNITY_ENABLE_DOUBLE 1
pub const CONFIG_UNITY_ENABLE_IDF_TEST_RUNNER 1
pub const CONFIG_VFS_SUPPRESS_SELECT_DEBUG_OUTPUT 1
pub const CONFIG_VFS_SUPPORT_TERMIOS 1
pub const CONFIG_SEMIHOSTFS_MAX_MOUNT_POINTS 1
pub const CONFIG_SEMIHOSTFS_HOST_PATH_MAX_LEN 128
pub const CONFIG_WL_SECTOR_SIZE_4096 1
pub const CONFIG_WL_SECTOR_SIZE 4096
pub const CONFIG_WIFI_PROV_SCAN_MAX_ENTRIES 16
pub const CONFIG_WIFI_PROV_AUTOSTOP_TIMEOUT 30
pub const CONFIG_WPA_MBEDTLS_CRYPTO 1

pub const CONFIG_ADC2_DISABLE_DAC CONFIG_ADC_DISABLE_DAC
pub const CONFIG_BROWNOUT_DET CONFIG_ESP32_BROWNOUT_DET
pub const CONFIG_BROWNOUT_DET_LVL_SEL_0 CONFIG_ESP32_BROWNOUT_DET_LVL_SEL_0
pub const CONFIG_COMPILER_OPTIMIZATION_LEVEL_DEBUG CONFIG_COMPILER_OPTIMIZATION_DEFAULT
pub const CONFIG_CONSOLE_UART_BAUDRATE CONFIG_ESP_CONSOLE_UART_BAUDRATE
pub const CONFIG_CONSOLE_UART_DEFAULT CONFIG_ESP_CONSOLE_UART_DEFAULT
pub const CONFIG_ESP32_APPTRACE_DEST_NONE CONFIG_APPTRACE_DEST_NONE
pub const CONFIG_ESP32_DEFAULT_PTHREAD_CORE_NO_AFFINITY CONFIG_PTHREAD_DEFAULT_CORE_NO_AFFINITY
pub const CONFIG_ESP32_PTHREAD_STACK_MIN CONFIG_PTHREAD_STACK_MIN
pub const CONFIG_ESP32_PTHREAD_TASK_NAME_DEFAULT CONFIG_PTHREAD_TASK_NAME_DEFAULT
pub const CONFIG_ESP32_PTHREAD_TASK_PRIO_DEFAULT CONFIG_PTHREAD_TASK_PRIO_DEFAULT
pub const CONFIG_ESP32_PTHREAD_TASK_STACK_SIZE_DEFAULT CONFIG_PTHREAD_TASK_STACK_SIZE_DEFAULT
pub const CONFIG_ESP32_RTC_CLOCK_SOURCE_INTERNAL_RC CONFIG_ESP32_RTC_CLK_SRC_INT_RC
pub const CONFIG_ESP_GRATUITOUS_ARP CONFIG_LWIP_ESP_GRATUITOUS_ARP
pub const CONFIG_FLASHMODE_DIO CONFIG_ESPTOOLPY_FLASHMODE_DIO
pub const CONFIG_FOUR_UNIVERSAL_MAC_ADDRESS CONFIG_ESP32_UNIVERSAL_MAC_ADDRESSES_FOUR
pub const CONFIG_GARP_TMR_INTERVAL CONFIG_LWIP_GARP_TMR_INTERVAL
pub const CONFIG_INT_WDT CONFIG_ESP_INT_WDT
pub const CONFIG_INT_WDT_CHECK_CPU1 CONFIG_ESP_INT_WDT_CHECK_CPU1
pub const CONFIG_INT_WDT_TIMEOUT_MS CONFIG_ESP_INT_WDT_TIMEOUT_MS
pub const CONFIG_IPC_TASK_STACK_SIZE CONFIG_ESP_IPC_TASK_STACK_SIZE
pub const CONFIG_LOG_BOOTLOADER_LEVEL_INFO CONFIG_BOOTLOADER_LOG_LEVEL_INFO
pub const CONFIG_MAIN_TASK_STACK_SIZE CONFIG_ESP_MAIN_TASK_STACK_SIZE
pub const CONFIG_MB_CONTROLLER_NOTIFY_QUEUE_SIZE CONFIG_FMB_CONTROLLER_NOTIFY_QUEUE_SIZE
pub const CONFIG_MB_CONTROLLER_NOTIFY_TIMEOUT CONFIG_FMB_CONTROLLER_NOTIFY_TIMEOUT
pub const CONFIG_MB_CONTROLLER_STACK_SIZE CONFIG_FMB_CONTROLLER_STACK_SIZE
pub const CONFIG_MB_EVENT_QUEUE_TIMEOUT CONFIG_FMB_EVENT_QUEUE_TIMEOUT
pub const CONFIG_MB_MASTER_DELAY_MS_CONVERT CONFIG_FMB_MASTER_DELAY_MS_CONVERT
pub const CONFIG_MB_MASTER_TIMEOUT_MS_RESPOND CONFIG_FMB_MASTER_TIMEOUT_MS_RESPOND
pub const CONFIG_MB_QUEUE_LENGTH CONFIG_FMB_QUEUE_LENGTH
pub const CONFIG_MB_SERIAL_BUF_SIZE CONFIG_FMB_SERIAL_BUF_SIZE
pub const CONFIG_MB_SERIAL_TASK_PRIO CONFIG_FMB_SERIAL_TASK_PRIO
pub const CONFIG_MB_SERIAL_TASK_STACK_SIZE CONFIG_FMB_SERIAL_TASK_STACK_SIZE
pub const CONFIG_MB_TIMER_GROUP CONFIG_FMB_TIMER_GROUP
pub const CONFIG_MB_TIMER_INDEX CONFIG_FMB_TIMER_INDEX
pub const CONFIG_MB_TIMER_PORT_ENABLED CONFIG_FMB_TIMER_PORT_ENABLED
pub const CONFIG_MONITOR_BAUD_115200B CONFIG_ESPTOOLPY_MONITOR_BAUD_115200B
pub const CONFIG_OPTIMIZATION_ASSERTIONS_ENABLED CONFIG_COMPILER_OPTIMIZATION_ASSERTIONS_ENABLE
pub const CONFIG_OPTIMIZATION_LEVEL_DEBUG CONFIG_COMPILER_OPTIMIZATION_DEFAULT
pub const CONFIG_POST_EVENTS_FROM_IRAM_ISR CONFIG_ESP_EVENT_POST_FROM_IRAM_ISR
pub const CONFIG_POST_EVENTS_FROM_ISR CONFIG_ESP_EVENT_POST_FROM_ISR
pub const CONFIG_REDUCE_PHY_TX_POWER CONFIG_ESP32_REDUCE_PHY_TX_POWER
pub const CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ABORTS CONFIG_SPI_FLASH_DANGEROUS_WRITE_ABORTS
pub const CONFIG_STACK_CHECK_NONE CONFIG_COMPILER_STACK_CHECK_MODE_NONE
pub const CONFIG_SUPPORT_TERMIOS CONFIG_VFS_SUPPORT_TERMIOS
pub const CONFIG_SUPPRESS_SELECT_DEBUG_OUTPUT CONFIG_VFS_SUPPRESS_SELECT_DEBUG_OUTPUT
pub const CONFIG_SYSTEM_EVENT_QUEUE_SIZE CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE
pub const CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE
pub const CONFIG_TASK_WDT CONFIG_ESP_TASK_WDT
pub const CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0 CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0
pub const CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU1 CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1
pub const CONFIG_TASK_WDT_TIMEOUT_S CONFIG_ESP_TASK_WDT_TIMEOUT_S
pub const CONFIG_TCPIP_RECVMBOX_SIZE CONFIG_LWIP_TCPIP_RECVMBOX_SIZE
pub const CONFIG_TCPIP_TASK_AFFINITY_NO_AFFINITY CONFIG_LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY
pub const CONFIG_TCPIP_TASK_STACK_SIZE CONFIG_LWIP_TCPIP_TASK_STACK_SIZE
pub const CONFIG_TCP_MAXRTX CONFIG_LWIP_TCP_MAXRTX
pub const CONFIG_TCP_MSL CONFIG_LWIP_TCP_MSL
pub const CONFIG_TCP_MSS CONFIG_LWIP_TCP_MSS
pub const CONFIG_TCP_OVERSIZE_MSS CONFIG_LWIP_TCP_OVERSIZE_MSS
pub const CONFIG_TCP_QUEUE_OOSEQ CONFIG_LWIP_TCP_QUEUE_OOSEQ
pub const CONFIG_TCP_RECVMBOX_SIZE CONFIG_LWIP_TCP_RECVMBOX_SIZE
pub const CONFIG_TCP_SND_BUF_DEFAULT CONFIG_LWIP_TCP_SND_BUF_DEFAULT
pub const CONFIG_TCP_SYNMAXRTX CONFIG_LWIP_TCP_SYNMAXRTX
pub const CONFIG_TCP_WND_DEFAULT CONFIG_LWIP_TCP_WND_DEFAULT
pub const CONFIG_TIMER_QUEUE_LENGTH CONFIG_FREERTOS_TIMER_QUEUE_LENGTH
pub const CONFIG_TIMER_TASK_PRIORITY CONFIG_FREERTOS_TIMER_TASK_PRIORITY
pub const CONFIG_TIMER_TASK_STACK_DEPTH CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH
pub const CONFIG_TIMER_TASK_STACK_SIZE CONFIG_ESP_TIMER_TASK_STACK_SIZE
pub const CONFIG_TOOLPREFIX CONFIG_SDK_TOOLPREFIX
pub const CONFIG_UDP_RECVMBOX_SIZE CONFIG_LWIP_UDP_RECVMBOX_SIZE

 */