[package]
name = "pic8259"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
novuskinc = { git = "https://github.com/new-kernel/novuskinc" }
pic8259 = "0.10.4"
spin = "0.9.8"
